variables:
  ROS_DISTRO: "kinetic"
  CI_SOURCE_PATH: "$CI_PROJECT_DIR"
  ROS_PARALLEL_JOBS: "-j4"

image: ros:kinetic-robot

before_script:
# before install
  - mkdir -p ~/ci_ws/src
  - cd ~/ci_ws
  - apt-get update
  - apt-get install -y python-catkin-tools
  - catkin init
# install
  - cd ~/ci_ws/src
  - git clone ${CI_REPOSITORY_URL}
  - cd ~/ci_ws
# This is if you configure your rosdep correctly
  - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO

kinetic-builder:
  stage: build
  script:
    - source /opt/ros/$ROS_DISTRO/setup.bash
    - cd ~/ci_ws
    - catkin build
    - source devel/setup.bash
    - catkin_make run_tests && catkin_make test
    - echo "Done with the tests"
  tags:
    - ros
